### ISSUE TITLE
SSLHandshakeException: sun.security.validator.ValidatorException: TLS Server certificate issued after 2019-04-16 and anchored by a distrusted legacy Symantec root

### ISSUE THREAD

**Issue by svalavuo** [philipparndt/groheondus-to-mqtt-gw#4]
Is this project still alive?
My installation stopped working 2020-03-12.
Is there a way to debug what's wrong with my settings?

- Samuli

**Comment by philipparndt** [comment]
Hi @svalavuo,
it is still up and running for me :)

I had once an issue where login was not longer possible (I guess due to change of a password policy).
I had to:
- open the following URL: https://idp2-apigw.cloud.grohe.com/v3/iot/oidc/login
- select "lost password"
- enter E-Mail Address
- copy the link from the E-Mail
- place it in browser
- replace `ondus://` with `https://` in the URL will will get delegated to. I then got an auth token.

After this steps everything was fine for me again.

**Comment by svalavuo** [comment]
Hi,
That didn't help for me.
I changed my password in Grohe site and in production/config/config.json
But my mosquitto doesn't get any messages. :-(

Is there any way to debug or get any information out of that docker?

- Samuli

**Comment by philipparndt** [comment]
You can type `docker logs <container id>` this should give us at least some hint.
Currently, there is no extended error logging. Do you have a chance to open this project in a Java IDE?
(IntelliJ, VSCode, Eclipse or https://www.gitpod.io/#https://github.com/philipparndt/groheondus-to-mqtt-gw)

**Comment by svalavuo** [comment]
Thanks for quick replies!

This is the message docker logs gives:
08:02:12.110 [main] INFO de.rnd7.groheondustomqtt.mqtt.GwMqttClient - Connecting MQTT client
08:02:51.732 [main] ERROR de.rnd7.groheondustomqtt.Main - sun.security.validator.ValidatorException: TLS Server certificate issued after 2019-04-16 and anchored by a distrusted legacy Symantec root CA: CN=thawte Primary Root CA - G3, OU="(c) 2008 thawte, Inc. - For authorized use only", OU=Certification Services Division, O="thawte, Inc.", C=US
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: TLS Server certificate issued after 2019-04-16 and anchored by a distrusted legacy Symantec root CA: CN=thawte Primary Root CA - G3, OU="(c) 2008 thawte, Inc. - For authorized use only", OU=Certification Services Division, O="thawte, Inc.", C=US
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at org.grohe.ondus.api.client.ApiClient.post(ApiClient.java:71)
        at org.grohe.ondus.api.actions.RefreshTokenAction.refresh(RefreshTokenAction.java:20)
        at org.grohe.ondus.api.OndusService.login(OndusService.java:69)
        at org.grohe.ondus.api.OndusService.login(OndusService.java:51)
        at de.rnd7.groheondustomqtt.grohe.GroheAPI.<init>(GroheAPI.java:20)
        at de.rnd7.groheondustomqtt.Main.<init>(Main.java:32)
        at de.rnd7.groheondustomqtt.Main.main(Main.java:71)
Caused by: sun.security.validator.ValidatorException: TLS Server certificate issued after 2019-04-16 and anchored by a distrusted legacy Symantec root CA: CN=thawte Primary Root CA - G3, OU="(c) 2008 thawte, Inc. - For authorized use only", OU=Certification Services Division, O="thawte, Inc.", C=US
        at sun.security.validator.SymantecTLSPolicy.checkNotBefore(SymantecTLSPolicy.java:194)
        at sun.security.validator.SymantecTLSPolicy.checkDistrust(SymantecTLSPolicy.java:177)
        at sun.security.validator.CADistrustPolicy$1.checkDistrust(CADistrustPolicy.java:54)
        at sun.security.validator.EndEntityChecker.check(EndEntityChecker.java:167)
        at sun.security.validator.Validator.validate(Validator.java:274)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)
        ... 27 common frames omitted

So, there is something wrong with Grohe certificate or my environment...

- Samuli

**Comment by svalavuo** [comment]
Hi again!
I tried to run docker image in my Asustor NAS and it gave exactly the same error.

- Samuli

**Comment by svalavuo** [comment]
Hi,
Can this be applied to docker container?
https://stackoverflow.com/questions/58437531/how-to-fix-javax-net-ssl-sslhandshakeexception-tls-server-certificate-issued-a

I changed the file inside container and it seems to work. The change seems to stay when container is restarted.

- Samuli

**Comment by philipparndt** [comment]
Hi I've pushed the image `pharndt/groheondusmqtt:unsafe-ca` can you test it? I still need to figure out another solution but I think this should work as a temporary workaround.
